name: Java Check

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v4

    - name: Install Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Compile all Java files
      run: |
        find . -name "*.java" | while read file; do
          dir=$(dirname "$file")
          javac -d "$dir/../classes" "$file"
        done