name: Java Check

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v4

    - name: Install Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Compile Java files individually
      run: |
        mkdir -p classes

        find . -name "*.java" -type f -print0 | while IFS= read -r -d '' file; do
          echo "Compiling $file"
          javac -d classes "$file" || true
        done