name: Java Check

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v4

    - name: Install Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Compile each course separately
      run: |
        find . -name "src" -type d | while read src; do
          echo "Compiling project in $src"
          mkdir -p "$src/../classes"
          javac -d "$src/../classes" $(find "$src" -name "*.java")
        done